import { useState, type FormEvent } from 'react';
import { ActionType, type PrivacyAction } from '@preflight/shared-types';
import { requestReport } from '../lib/api-client';
import { ConnectWallet } from '../components/ConnectWallet';
import { Report, type ReportResponse } from './Report';

export function Home() {
  const [type, setType] = useState<ActionType>(ActionType.UnshieldAction); const [token, setToken] = useState(''); const [amount, setAmount] = useState(''); const [fundingAddress, setFundingAddress] = useState(''); const [recipient, setRecipient] = useState(''); const [targetToken, setTargetToken] = useState(''); const [executor, setExecutor] = useState(''); const [report, setReport] = useState<ReportResponse>(); const [error, setError] = useState(''); const needsRecipient = type !== ActionType.ShieldAction;
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const action = (type === ActionType.PrivateSwapAction ? { type, token, amount, recipient, targetToken, executor } : { type, token, amount, recipient: needsRecipient ? recipient : fundingAddress }) as PrivacyAction; setReport(await requestReport<ReportResponse>({ action, fundingAddress, destinationAddress: recipient || fundingAddress })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load report'); } };
  return <><section className="mt-10 rounded-lg border border-[#cbd8cc] bg-white/70 p-5 md:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">Analyze a transaction</h2><p className="mt-1 text-sm text-[#53665a]">Use a wallet or enter the exact call details.</p></div><ConnectWallet onAddress={setFundingAddress} /></div><form onSubmit={submit} className="mt-6 grid gap-4 md:grid-cols-2"><label>Action type<select value={type} onChange={e => setType(e.target.value as ActionType)} className="field"><option value={ActionType.ShieldAction}>Shield</option><option value={ActionType.PrivateTransferAction}>Private transfer</option><option value={ActionType.UnshieldAction}>Unshield / withdraw</option><option value={ActionType.PrivateSwapAction}>Private swap</option></select></label><label>Token<input required value={token} onChange={e => setToken(e.target.value)} placeholder="0x…" className="field" /></label><label>Amount (base units)<input required value={amount} onChange={e => setAmount(e.target.value)} inputMode="numeric" placeholder="238" className="field" /></label><label>Funding address<input required value={fundingAddress} onChange={e => setFundingAddress(e.target.value)} placeholder="0x…" className="field" /></label>{needsRecipient && <label>Recipient / destination<input required value={recipient} onChange={e => setRecipient(e.target.value)} placeholder="0x…" className="field" /></label>}{type === ActionType.PrivateSwapAction && <><label>Target token<input required value={targetToken} onChange={e => setTargetToken(e.target.value)} placeholder="0x…" className="field" /></label><label>Executor<input required value={executor} onChange={e => setExecutor(e.target.value)} placeholder="0x…" className="field" /></label></>}<button className="rounded-lg bg-[#a3432b] px-5 py-3 font-bold text-white hover:bg-[#873620] md:col-span-2">Generate privacy report</button></form>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}</section><Report report={report} /></>;
}
